Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -956,12 +956,12 @@ fi
 #############################################
 
  # First thing to do is check if this machine is Debian
-# source /etc/os-release
-#if [[ "$ID" != 'debian' != 'ubuntu']]; then
-# ScriptMessage
-# echo -e "[\e[1;31mError This script is for Debian or Ubuntu only, exiting..." 
- #exit 1
-#fi
+ source /etc/os-release
+if [[ "$ID" != 'debian']]; then
+ ScriptMessage
+ echo -e "[\e[1;31mError This script is for Debian or Ubuntu only, exiting..." 
+ exit 1
+fi
 
 
  # Now check if our machine is in root user, if not, this script exits
